In [1]:
from IPython.core.display import HTML
css_file = '../../../style/style01.css'
HTML(open(css_file, "r").read())

FileNotFoundError: [Errno 2] No such file or directory: '../../../style/style01.css'

> Content under [Creative Commons Attribution license CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/), [code under MIT license (c)](http://en.wikipedia.org/wiki/MIT_License) 2016 Sergio Rojas (srojas@usb.ve). 

<b> <center> 
# NumPy and its functionality
<font color='red'>
# Working with Numpy Array </font>
</center></b>


As presented in Wikipedia, NumPy  (pronounced "Numb Pie" or sometimes "Numb pee") is an extension to the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays [ [https://en.wikipedia.org/wiki/NumPy]( https://en.wikipedia.org/wiki/NumPy) ].

Accordingly, NumPy provides the multi-dimensional arrays and matrices and other data objects structures on which SciPy relays and builts its high performance operating functionality.

In [5]:
import numpy as np

 ** Create the array from a python list **

In [6]:
x = [0.0, 1.5, 3.0, 4.5, 6.0, ];
y = [0.0, 0.86, 1.71, 2.57, 3.43, 4.29, 5.14, 6.0];
print(type(x)); 
print(type(y))

<class 'list'>
<class 'list'>


In [7]:
xx = np.array(x);
yy = np.array(y);
print(type(xx)); 
print(type(yy))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
print(xx)
print(type(xx))

[ 0.   1.5  3.   4.5  6. ]
<class 'numpy.ndarray'>


In [9]:
print(yy)
print(type(yy))

[ 0.    0.86  1.71  2.57  3.43  4.29  5.14  6.  ]
<class 'numpy.ndarray'>


 ** Create the array typing its values **

In [10]:
xxx = np.array([0, 1.5, 3., 4.5, 6. ])

In [11]:
print(xxx)
print(type(xxx))

[ 0.   1.5  3.   4.5  6. ]
<class 'numpy.ndarray'>


 ** Inquire about the shape, size, dimensionality and type of the elements in the array **

In [12]:
print(np.shape(xx)); print(np.size(xx)); 

(5,)
5


In [13]:
print(np.ndim(xx)); print(len(xx)); print(xx.dtype)

1
5
float64


** Re-arrange the elements in the array  **

In [14]:
nfilas = 2;
ncolumns = 4
# rule: nfilas*ncolumns = array size
Y = np.reshape(yy, (nfilas, ncolumns)) 
print(Y)

[[ 0.    0.86  1.71  2.57]
 [ 3.43  4.29  5.14  6.  ]]


In [15]:
X, Y  = np.meshgrid(xx,yy);
print(type(X)); 
print(type(Y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [16]:
print(X)

[[ 0.   1.5  3.   4.5  6. ]
 [ 0.   1.5  3.   4.5  6. ]
 [ 0.   1.5  3.   4.5  6. ]
 [ 0.   1.5  3.   4.5  6. ]
 [ 0.   1.5  3.   4.5  6. ]
 [ 0.   1.5  3.   4.5  6. ]
 [ 0.   1.5  3.   4.5  6. ]
 [ 0.   1.5  3.   4.5  6. ]]


In [17]:
print(Y)

[[ 0.    0.    0.    0.    0.  ]
 [ 0.86  0.86  0.86  0.86  0.86]
 [ 1.71  1.71  1.71  1.71  1.71]
 [ 2.57  2.57  2.57  2.57  2.57]
 [ 3.43  3.43  3.43  3.43  3.43]
 [ 4.29  4.29  4.29  4.29  4.29]
 [ 5.14  5.14  5.14  5.14  5.14]
 [ 6.    6.    6.    6.    6.  ]]


In [18]:
print(np.shape(Y)); print(np.size(Y)); 
print(np.ndim(Y)); print(len(Y)); print(Y.dtype)

(8, 5)
40
2
8
float64


** Finding and replacing elements in an array **

In [19]:
temp1=Y[1,3]; temp2=Y[4,4]
print(Y[1,3]); print(Y[4,4])

0.86
3.43


In [20]:
Y[1,3] = np.nan ; Y[4,4] = np.inf
print(Y[1,3]); print(Y[4,4])

nan
inf


In [21]:
np.isnan(Y)

array([[False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [22]:
np.isinf(Y)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [23]:
print(np.where(np.isnan(Y)));
print(np.where(np.isinf(Y)));

(array([1]), array([3]))
(array([4]), array([4]))


In [24]:
Y[np.where(np.isnan(Y))] = temp1;
Y[np.where(np.isinf(Y))] = temp2;
print(Y)

[[ 0.    0.    0.    0.    0.  ]
 [ 0.86  0.86  0.86  0.86  0.86]
 [ 1.71  1.71  1.71  1.71  1.71]
 [ 2.57  2.57  2.57  2.57  2.57]
 [ 3.43  3.43  3.43  3.43  3.43]
 [ 4.29  4.29  4.29  4.29  4.29]
 [ 5.14  5.14  5.14  5.14  5.14]
 [ 6.    6.    6.    6.    6.  ]]


In [25]:
print(np.where(Y > 3))

(array([4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))


** Special methods to create arrays **

In [26]:
uniformsp =np.linspace(-1,1,4)
print(uniformsp)

[-1.         -0.33333333  0.33333333  1.        ]


In [27]:
logsp = np.logspace(-1,1,4)
print(logsp)

[  0.1          0.46415888   2.15443469  10.        ]


In [28]:
O = np.zeros((3,5), dtype=float)
print(O)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [29]:
U=np.ones((4,3), dtype=int)
print(U)


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [30]:
I=np.identity(3, dtype=int)
print(I)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
D=np.eye(4,3)
print( D)
D=np.eye(4)
print('Identity matrix: \n', D)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
Identity matrix: 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [35]:
D=np.eye(4,3,k = 1)
print( D)

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [36]:
D=np.eye(4,3,k = -1)
print( D)

[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [37]:
D=np.eye(4,3,k=1) + np.eye(4,3,k=-1)
print( D)

[[ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [38]:
A=3.0*( np.eye(5,4,k=4) + np.eye(5,4,k=-4) )
print(" A = \n {0}".format(A))

 A = 
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 3.  0.  0.  0.]]


In [39]:
from IPython.core.display import HTML

<b> References </b>

* ** Chapter 2: Learning SciPy for Numerical and Scientific Computing - Second Edition **<br>
<https://github.com/rojassergio/Learning-Scipy>

In [43]:
HTML('<iframe src=http://nbviewer.jupyter.org/github/rojassergio/Learning-Scipy/blob/master/Chapter2/7702OS_Chap_02_rev20141229.ipynb width=950 height=500></iframe>')

* **Numpy Tutorial**<br>
<http://wiki.scipy.org/Tentative_NumPy_Tutorial>

In [44]:
HTML('<iframe src=http://wiki.scipy.org/Tentative_NumPy_Tutorial/ width=950 height=350></iframe>')

* ** NumPy Reference **<br>
<http://docs.scipy.org/doc/numpy/reference/index.html>

In [46]:
HTML('<iframe src=http://docs.scipy.org/doc/numpy/reference/index.html width=950 height=350></iframe>')

* ** NumPy: creating and manipulating numerical data **<br>
<http://www.scipy-lectures.org/intro/numpy/numpy.html>
<br>
* ** Array creation routines **<br>
<http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html>
<br>
* ** Array manipulation routines **<br>
<http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html>
<br>
* ** Numpy Array objects **<br>
<http://www.scipy-lectures.org/intro/numpy/array_object.html>
<br>
* ** Numpy Quick start Tutorial **<br>
<https://docs.scipy.org/doc/numpy-dev/user/quickstart.html>
<br>
* ** Numpy Data type objects **<br>
<http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html>
<br>
* ** The N-dimensional array (ndarray) **<br>
<http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html>
<br>
* ** Masked array operations **<br>
<http://docs.scipy.org/doc/numpy/reference/routines.ma.html>

> Content under [Creative Commons Attribution license CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/), [code under MIT license (c)](http://en.wikipedia.org/wiki/MIT_License) 2016 Sergio Rojas (srojas@usb.ve) 